server:
  port: 8180
spring:
  application:
    name: ai_server
  cloud:
    nacos:
      server-addr: 192.168.85.129:8848
  elasticsearch:
    uris: 192.168.85.129:9200
  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: custom-index
    openai:
      base-url: ${SPRING_AI_OPENAI_BASE_URL:https://openrouter.ai/api}
      api-key: ${SPRING_AI_OPENAI_API_KEY:${OPENROUTER_API_KEY:}}
      chat:
        options:
          model: ${SPRING_AI_OPENAI_MODEL:deepseek/deepseek-chat-v3-0324:free}

