server:
  port: 8091
spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connect-timeout: 30000
            read-timeout: 120000
            logger-level: basic
  elasticsearch:
    uris: 192.168.85.129:9200
#  rabbitmq:
#    host: 192.168.85.129
#    port: 5672
#    username: ${RABBITMQ_USERNAME:guest}
#    password: ${RABBITMQ_PASSWORD:guest}
#    virtual-host: /
#    listener:
#      simple:
#        # 手动确认模式
#        acknowledge-mode: manual
#        # 并发消费者数量
#        concurrency: 2
#        max-concurrency: 5
#        # 预取数量
#        prefetch: 1
#        # 重试配置
#        retry:
#          enabled: true
#          initial-interval: 1000
#          max-attempts: 3
#          multiplier: 2
  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: custom-index
        similarity: cosine
    zhipuai:
      api-key: ${SPRING_AI_ZHIPU_API_KEY:ce2ff390ca4245aca42d30742c8f0948.DTmePxPPh3omhU8i}
      chat:
        options:
          model: ${SPRING_AI_ZHIPU_MODEL:glm-4.5}
      embedding:
        options:
          model: embedding-3
    retry:
      max-attempts: 5
      backoff:
        initial-interval: 2s
        max-interval: 30s
        multiplier: 2

logging:
  level:
    com.example.spring_ai_demo.client: DEBUG
    com.example.spring_ai_demo.service.MultiThreadElasticsearchRAGService: INFO

# 线程池配置
thread-pool:
  vector-process:
    core-size: 3
    max-size: 5
    queue-capacity: 20
  data-fetch:
    core-size: 5
    max-size: 10
    queue-capacity: 50
