server:
  port: 8091
spring:
  elasticsearch:
    uris: 192.168.85.129:9200
  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: custom-index
        similarity: cosine
    zhipuai:
      api-key: ${SPRING_AI_ZHIPU_API_KEY:ce2ff390ca4245aca42d30742c8f0948.DTmePxPPh3omhU8i}
      chat:
        options:
          model: ${SPRING_AI_ZHIPU_MODEL:glm-4.5}
      embedding:
        options:
          model: embedding-3
    retry:
      max-attempts: 5
      backoff:
        initial-interval: 2s
        max-interval: 30s
        multiplier: 2

logging:
  level:
    com.example.spring_ai_demo.client: DEBUG
