server:
  port: 8180
spring:
  application:
    name: ai_server
  cloud:
    nacos:
      server-addr: 192.168.85.129:8848
  elasticsearch:
    uris: 192.168.85.129:9200
  ai:
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: custom-index
    zhipuai:
      api-key: ${SPRING_AI_ZHIPU_API_KEY:}
      chat:
        options:
          model: ${SPRING_AI_ZHIPU_MODEL:glm-4.5}
      embedding:
        options:
          model: embedding-3
          dimensions: 1536
